# Generated by Django 3.1.6 on 2021-02-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], default='M', max_length=10)),
                ('book_name', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=10)),
                ('ask_book', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
